# Generated by Django 5.0.6 on 2024-07-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='departure',
            new_name='origin',
        ),
    ]
