# Generated by Django 5.0.7 on 2024-07-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_rec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilog',
            name='log_time',
        ),
    ]
