# Generated by Django 5.0.7 on 2024-07-31 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_rec', '0002_remove_apilog_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
